config/routes.rb
Portfolio::Application.routes.draw do

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"},
                   controllers: {omniauth_callbacks: "omniauth_callbacks"}

  resources :posts do
    resources :comments
  end

  resources :projects do
    resources :comments
  end

  scope ":locale" do
  end

   root :to => 'posts#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  #attr_accessible :approved, :author, :author_email, :author_url, :content, :referrer, :user_agent, :user_ip
  belongs_to :commentable, polymorphic: true
  validates :content,      presence: true
  validates :author_email, presence: true
  validates :author,       presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :load_commentable

  def create
    @comment = @commentable.comments.new(comment_params)
    if @comment.save
      flash[:notice] = "Comment is awaiting moderation"
      redirect_to @commentable, notice: "Comment is awaiting moderation"
    else
      instance_variable_set("@#{@resource.singularize}".to_sym, @commentable)
      render template: "#{@resource}/show"
    end
  end

def update
     @comment = Comment.find(params[:id])
     if @comment.update_attributes(params[:comment])
       flash[:notice] = "Comment Approved!"
       redirect_to @comment.commentable
     else
       flash[:alert] = "Comment not approved."
       redirect_to post_path(@comment.commentable)
     end
   end

def destroy
      @comment = Comment.find(params[:id])
      @comment.destroy
      flash[:notice] = "Comment Destroyed!"
      redirect_to post_path(@comment.commentable)
end

private

 def load_commentable
   resource, id = request.path.split('/')[1,2]
   @commentable = resource.singularize.classify.constantize.find(id)
 end


 def comment_params
   params.require(:comment).permit(:author,
                                   :author_url,
                                   :author_email,
                                   :content,
                                   :referrer,
                                   :approved,
                                   :commentable)
  end
end

app/views/comments/_comment.html.erb
<div class="comment">
<% @comments.each do |comment| %>
<tr>
  <td><b>Name:</b>   <%= comment.author %></td><br />
  <td><b>Comment:</b>   <%= comment.content %></td>
</tr>
<% end %>


<% if current_user && current_user.editor? %>
  <tr>
    <% if comment.approved? %>
      <td><%= button_to 'Delete', polymorphic_path([@commentable, comment]), method: :delete, class: "btn" %></td>
    <% else %>
      <td><%= button_to 'Approve', polymorphic_path([@commentable, comment], comment: { approved: true }), method: :put, class: "btn" %></td>
    <% end %>
  </tr>
<% end %>
</div>

app/views/comments/_form.html.erb
<div class="comment_form">
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_for [@commentable, @comment] do |f| %>
    <div class="field">
      <%= f.label :author, "Your name" %>
      <%= f.text_field :author %>
    </div>
    <div class="field">
      <%= f.label :author_email, "Your email" %>
      <%= f.text_field :author_email %>
    </div>
    <div class="field">
      <%= f.label :author_url, "Your URL" %>
      <%= f.text_field :author_url %>
    </div>
    <div class="field">
      <%= f.label :content, "Your Comment" %>
      <%= f.text_field :content %>
    </div>
    <%= f.hidden_field :referrer, value: request.referrer %>
    <%= f.hidden_field :commentable_id,  value: @commentable.id %>
    <div class="actions">
      <%= f.submit "Submit comment for approval" %>
    <div>
  <% end %>
</div><!-- .comment_form -->

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <tr>
    <th>Commenter</th>
    <th>Body</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comments.each do |comment| %>
  <tr>
    <td><%= comment.author %></td>
    <td><%= comment.content %></td>
    <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
    <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />