config/routes.rb
Portfolio::Application.routes.draw do

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"},
                   controllers: {omniauth_callbacks: "omniauth_callbacks"}

  resources :posts do
    resources :comments
  end

  resources :projects do
    resources :comments
  end

  scope ":locale" do
  end

   root :to => 'posts#index'

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :comments, as: :commentable
  mount_uploader :image, ImageUploader
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
   before_filter :set_project, only: [:show, :edit, :update, :destroy]
   before_filter :authenticate_user!, except: [:show, :index]
  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])
    @commentable = @project
    @comments = @commentable.comments
    @comment = Comment.new

    respond_to do |format|
      format.html # show.html.erb
      format.js
      format.json { render json: @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
    respond_to do |format|
      format.html
      format.js
    end
  end

  # PROJECT /projects
  # PROJECT /projects.json
  def create
    @project = Project.create(params[:project])
    respond_to do |format|
      format.html { redirect_to projects_url }
      format.js   {}
    end
  end


  # PUT /projects/1
  # PUT /projects/1.json
  def update
     @project = Project.find(params[:id])
     if @project.update_attributes(params[:project])
      flash[:success] = "Project Updated!"
      redirect_to @project
     else
      format.html { render :edit }
      format.json { render json: @project.errors, status: :unprocessable_entity }
     end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.destroy(params[:id])
    respond_to do |format|
      format.html { redirect_to projects_url  }
      format.js
    end
  end


  private

    def set_project
      @project = Project.find(params[:id])
    end

    def project_params
      params.require(:project).permit(:name, :details, :content, :name, :author_id)
    end
  end

app/views/projects/_form.html.erb
<%= form_for @project, html: { multipart: true } do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :details %><br />
    <%= f.text_area :details %>
  </div>
  <div class="field">
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/_header.html.erb
<header>

<div class="cover" style="background-image: url(<%= asset_path 'nyc-subway.jpg' %>)">

<div class="coverOverlay"></div>


<div class="profileName">

<h1>Underground Rails</h1>

<p></p>

</div>

</div>

<nav>

<ul class="etabs">

<li class="tab"><%= link_to 'Home', root_path %><span class="tabIcon glyphicon glyphicon-envelope"></span><span class="tabText"></span></a></li>

<li class="tab"><%= link_to 'Portfolio', projects_path %><span class="tabIcon glyphicon glyphicon-briefcase"></span><span class="tabText"></span></a></li>

<li class="tab"><%= link_to 'Blog', posts_path %><span class="tabIcon glyphicon glyphicon-pencil"></span><span class="tabText"></span></a></li>

<li class="tab">
  <%= render 'devise/menu/registration_items' %><span class="tabIcon glyphicon glyphicon-pencil"></span><span class="tabText"></span>
</li>

<li class="tab">
  <%= render 'devise/menu/login_items' %><span class="tabIcon glyphicon glyphicon-pencil"></span><span class="tabText"></span>
</li>

<li class="tab">
  <%= link_to "Sign in with Twitter", user_omniauth_authorize_path(:twitter) %>
</li>
</ul>


</nav>

</header>

app/views/projects/_project.html.erb
<%= form_for project do |f| %>
  <%= link_to project.name, project %>
  </li><%= link_to "(remove)", project, method: :delete, data: {confirm: "Are you sure?"}, remote: true %>
<% end %>

app/views/projects/_show.html.erb
<p id="notice"><%= notice %></p>
<h1><%= @project.name %></h1>
    <h6>10/11/13</h6>
    <td><%= @project.details %></td>

<%= image_tag @project.image_url %>
<%= link_to 'Edit', edit_project_path(@project), id: "edit_link" %> |
<%= link_to 'Back', projects_path, id: "back_link" %>
<br />
<br />
<ul>
  <% if @project.comments.any? %>
    <% @project.comments.each do |comment| %>

      <% if current_user.nil? %>
        <% if comment.approved %>
          <%= render comment %>
        <% end %>

      <% elsif current_user.editor? %>
        <%= render comment %>

      <% else %>
        <% if comment.approved %>
          <%= render comment %>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
</ul>


<% if current_user %>
  <h4> Add a Comment </h4>
  <%= render '/comments/form' %>
<% else %>
  <h6> Please <%= link_to 'sign in via Twitter', user_omniauth_authorize_path(:twitter) %> to leave a comment!</h6>
<% end %>
</div>

app/views/projects/create.js.erb
$("<%= escape_javascript(render @project) %>").appendTo("#projects");
$("#new_project").remove();
$("#new_link").show();

app/views/projects/destroy.js.erb
$('#edit_project_<%= @project.id %>').remove();

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/edit.js.erb
$('#edit_link').hide().after('<%= j render("form") %>');

app/views/projects/index.html.erb
<h2>Projects</h2>

<%= link_to "New Project", new_project_path, id: "new_link", :remote => true %>

<div class="projects" id="projects">
  <ul id="projects">
    <%= render @projects %>
  </ul>
</div>

<br />

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/new.js.erb
$('#new_link').hide().after('<%= j render("form") %>');

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>
<h1><%= @project.name %></h1>
    <span class="timestamp">at <%= @project.created_at %></span>
    <td><%= @project.details %></td>

<%= image_tag @project.image_url %>
<%= link_to 'Edit', edit_project_path(@project), id: "edit_link" %> |
<%= link_to 'Back', projects_path, id: "back_link" %>
<br />
<br />
<ul>
  <% if @project.comments.any? %>
    <% @project.comments.each do |comment| %>

      <% if current_user.nil? %>
        <% if comment.approved %>
          <%= render comment %>
        <% end %>

      <% elsif current_user.editor? %>
        <%= render comment %>

      <% else %>
        <% if comment.approved %>
          <%= render comment %>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
</ul>


<% if current_user %>
  <h4> Add a Comment </h4>
  <%= render '/comments/form' %>
<% else %>
  <h6> Please <%= link_to 'sign in via Twitter', user_omniauth_authorize_path(:twitter) %> to leave a comment!</h6>
<% end %>
</div>

app/views/projects/show.js.erb
$('#new_link').hide().after('<%= j render("show") %>');
$('#projects').hide();

app/views/projects/update.js.erb
  $('#edit_project_<%= @project.id %>').appendTo('#projects');