config/routes.rb
Portfolio::Application.routes.draw do

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"},
                   controllers: {omniauth_callbacks: "omniauth_callbacks"}

  resources :posts do
    resources :comments
  end

  resources :projects do
    resources :comments
  end

  scope ":locale" do
  end

   root :to => 'posts#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :author, class_name: "User"
  has_many :comments, as: :commentable
  scope :published, where(published: true)

  def publish!
    self.published = true
    save!
  end
end

app/controllers/posts_controller.rb
# Blog posts controller
class PostsController < ApplicationController
  before_filter :set_post, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, except: [:index, :show]

  # GET /posts
  # GET /posts.json
  def index
    @posts = policy_scope(Post)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])
    @commentable = @post
    @comments = @commentable.comments
    @comment = Comment.new

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    authorize @post
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    authorize @post
    respond_to do |format|
      if @post.save
        current_user.posts << @post
        format.html do
          redirect_to @post, notice: 'Post was successfully created.'
        end
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    authorize @post
    respond_to do |format|
      if @post.update_attributes(post_params)
        format.html do
          redirect_to @post, notice: 'Post was successfully updated.'
        end
        format.json { head :no_content }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    authorize @post
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was deleted." }
      format.json { head :no_content }
    end
  end

private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :content, :author_id, :published)
  end
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_header.html.erb
<header>

<div class="cover" style="background-image: url(<%= asset_path 'nyc-subway.jpg' %>)">

<div class="coverOverlay"></div>


<div class="profileName">

<h1>Underground Rails</h1>

<p></p>

</div>

</div>

<nav>

<ul class="etabs">

<li class="tab"><%= link_to 'Home', root_path %><span class="tabIcon glyphicon glyphicon-envelope"></span><span class="tabText"></span></a></li>

<li class="tab"><%= link_to 'Portfolio', projects_path %><span class="tabIcon glyphicon glyphicon-briefcase"></span><span class="tabText"></span></a></li>

<li class="tab"><%= link_to 'Blog', posts_path %><span class="tabIcon glyphicon glyphicon-pencil"></span><span class="tabText"></span></a></li>

<li class="tab">
  <%= render 'devise/menu/registration_items' %><span class="tabIcon glyphicon glyphicon-pencil"></span><span class="tabText"></span>
</li>

<li class="tab">
  <%= render 'devise/menu/login_items' %><span class="tabIcon glyphicon glyphicon-pencil"></span><span class="tabText"></span>
</li>

<li class="tab">
  <%= link_to "Sign in with Twitter", user_omniauth_authorize_path(:twitter) %>
</li>
</ul>


</nav>

</header>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="content">
  <div class="blog">
   <div class="row">
    <div class="col-md-8">
      <div class="panel">
        <div class="panel-heading">Blog</div>
        <div class="container">
          <div class="singlePost">
      <% @posts.each do |post| %>
        <tr id="<%= dom_id(post) %>">
          <h3><%= link_to post.title, post %></h3>
          <div class="description">
            <div class="descriptionSingle">
              <span><b>&nbsp;By: Scott Golembiewski</b></span>
              <span class="timestamp">at <%= l post.created_at, format: :short %></span>
            </div></div>
            <p><%= markdown(post.content).html_safe %></p><br><br>
          <% if policy(post).update? %>
              <%= link_to 'Edit', edit_post_path(post), class: "btn btn-default" %>
              <%= "Published" if post.published %>
              <%= button_to 'Publish', post_path(post, post: { published: true }), method: :put, class: "btn btn-default" %>
          <% end %>
          <% if policy(post).destroy? %>
            <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } , class: "btn btn-danger" %>
          <% end %>
      <% end %>
    </div>
  </div>
    <div class="clearfix"></div>
  </div>
</div>
    <div class="col-md-4">
              <div class="panel">
                        <div class="panel-heading">Categories</div>
                                <ul class="blogCategory">
                                <li><span class="icon glyphicon glyphicon-chevron-right"></span><span class="text"><a href="#">Rails</a></span><div class="clearfix"></div></li>
                                  <li><span class="icon glyphicon glyphicon-chevron-right"></span><span class="text"><a href="#">Gems</a></span><div class="clearfix"></div></li>
                                  <li><span class="icon glyphicon glyphicon-chevron-right"></span><span class="text"><a href="#">Testing</a></span><div class="clearfix"></div></li>
                                  <li><span class="icon glyphicon glyphicon-chevron-right"></span><span class="text"><a href="#">Heroku</a></span><div class="clearfix"></div></li>
                                    <li><span class="icon glyphicon glyphicon-chevron-right"></span><span class="text"><a href="#">Ruby</a></span><div class="clearfix"></div></li>
                                </ul>
                        </div>

                            <!-- Tweet -->

                            <!-- Tweet -->
                        </div>
                    </div>
                </div>








<%= link_to 'New Post', new_post_path, class: "btn btn-primary" if policy(Post).create? %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div class="comment">
<p>

  <h3><%= @post.title %></h3>
</p>
&nbsp;
<p><b>&nbsp;By: Scott Golembiewski</b>
  <span class="timestamp">at <%= l @post.created_at, format: :short %></span>
  <br>
</p>

<p>
  <%= markdown(@post.content).html_safe %>
</p>
<br />
<% if current_user && current_user.editor? %>
    <%= link_to 'Edit', edit_post_path(@post) %> |
    <%= link_to 'Back', posts_path %>
  <% else %>
<% end %>
<br />
<br />
<ul>
  <% if @post.comments.any? %>
    <% @post.comments.each do |comment| %>

      <% if current_user.nil? %>
        <% if comment.approved %>
          <%= render comment %>
        <% end %>

      <% elsif current_user.editor? %>
        <%= render comment %>

      <% else %>
        <% if comment.approved %>
          <%= render comment %>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
</ul>


<% if current_user %>
  <h4> Add a Comment </h4>
  <%= render '/comments/form' %>
<% else %>
  <h6> Please <%= link_to 'sign in via Twitter', user_omniauth_authorize_path(:twitter) %> to leave a comment!</h6>
<% end %>
</div>